AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for private EKS cluster

Parameters:
  CodeBuildSGId:
    Type: AWS::EC2::SecurityGroup::Id
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  ServiceRoleArn:
    Type: String
    Description: IAM Role ARN for CodeBuild

Resources:
  MyCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: eks-deploy-project
      ServiceRole: !Ref ServiceRoleArn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      Source:
        Type: CODECOMMIT
        Location: https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/my-repo
      VpcConfig:
        SecurityGroupIds:
          - !Ref CodeBuildSGId
        Subnets: !Ref PrivateSubnetIds
        VpcId: !Ref VpcId

Outputs:
  CodeBuildProjectName:
    Value: !Ref MyCodeBuildProject
